!!com.dongao.DaQsAiTest.FileDto.CaseYamlFileDto
description: /courseApi/course/V1/courseTimeConfig 接口测试用例
name: courseTimeConfig
steps:
- action: courseTimeConfig
  api: qs_course_courseTimeConfig
  assertparams: {expect: '2', matcher: equalTo, assertparam: obj}
  params: {userExtendId: '2095', playInfo: '%7B%22planType%22%3A43%2C%22teacherId%22%3A23%2C%22lectureList%22%3A%5B%7B%22sort%22%3A2%2C%22lectureId%22%3A885%7D%5D%2C%22planId%22%3A12603%2C%22planUserExtendId%22%3A2095%7D',
    studyFrom: '2', userId: '1889', lectureId: '885'}
